== Predeployment steps

Complete the following steps before you deploy the Quick Start. 

=== Load a tabular dataset into Snowflake

Load a tabular dataset, such as a CSV file, into Snowflake, and put it in a Snowflake table. For instance, you can use the Abalone dataset, originally from the https://archive.ics.uci.edu/ml/datasets/abalone[University of California Irvine (UCI) Machine Learning Repository^].

=== Generate and upload the layer and Lambda code to an existing S3 bucket

The Snowflake Python connector is not part of the AWS Lambda runtime. Use a Lambda layer to load the Snowflake Python connector into Lambda. The Lambda layer .zip file is hosted in a publicly accessible S3 bucket (sagemaker-sample-files) that this CloudFormation template refers to. 

Lambda layers take a .zip file with the libraries (formatted according to the language used) from S3 and load them into the Lambda runtime environment. For details, refer to https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html[Creating and sharing Lambda layers^]).

==== (Optional) Manually generate the .zip file that contains the layer code

If you want to generate the Lambda layer manually for development or testing, follow these instructions. Use the script `generate-layer.sh`, located in the `customer-stack/` directory, to download the needed files.

. From a Linux terminal, run the script as follows:
+
....
% cd customer-stack/
% bash generate-layer.sh
% cd layer/snowflake-connector-python/
% zip -r snowflake-connector-python-<version>.zip .
....
+
These commands generate a file called `snowflake-connector-python-.zip`, which contains the libraries for the Lambda function.

. Upload the generated file to your S3 bucket, and use the corresponding S3 URL as a reference for your Lambda layer.

==== (Optional) Manually generate the .zip file that contains the Lambda code

The Lambda function can't be specified inline on the CloudFormation template. Customers can see and edit it after the stack is created. 

Load the libraries as follows:

. Zip the Lambda Python code, and upload the .zip file to the same S3 bucket where you uploaded the layer .zip file in the previous section.

. From a Linux terminal, run:
+
....
% cd customer-stack/
zip -r create-resources-<version>.zip create-resources.py
....
+
These commands generate a file called `create-resources-.zip`, which contains the Lambda code.

. Upload the generated file to your S3 bucket, and use the corresponding S3 URL as a reference for your Lambda function code.
